language: c++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  # OSX dependencies
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt4; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install exiv2; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libraw; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install quazip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install opencv; fi

  - mkdir build
  - cd build

script:
  - cmake ../ImageLounge/.
  - make
