image: Visual Studio 2019
configuration: Release
skip_commits:
  files:
    - '.github/*'
    - '.travis.yml'
    - '.gitignore'
    - '*.md'

environment:
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QT5: C:\Qt\5.14.1\msvc2017_64
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
      ARCHITECTURE: x86_64
      WARNINGS_AS_ERRORS: ON

install:

    # - appveyor DownloadFile https://github.com/opencv/opencv/releases/download/4.3.0/opencv-4.3.0-vc14_vc15.exe -FileName opencv.zip
    # - 7z x opencv.zip -o.\3rd-party\opencv > nul
    - git submodule update --init --recursive
    # my machine:
    #  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"

    - call 3rd-party/build.bat
    - call "%VCVARS%"
    - cd ImageLounge
    - mkdir build
    - cd build
    - cmake -DENABLE_TRANSLATIONS=ON -DCMAKE_PREFIX_PATH=%QT5% -DENABLE_OPENCV=OFF -DENABLE_RAW=OFF -DENABLE_TIFF=OFF -DENABLE_QUAZIP=OFF ..
 
build:
  project: build/nomacs.sln
  parallel: true
  verbosity: minimal

after_build:
  - copy %CONFIGURATION%\nomacs.exe .

artifacts:
- path: 'build\libavif_vs2019_x64_*.zip'
  name: Static Lib and Includes
- path: 'build\*.exe'
  name: Basic apps
