image: Visual Studio 2019
configuration: Release
skip_commits:
  files:
    - '.github/*'
    - '.travis.yml'
    - '.gitignore'
    - '*.md'

environment:
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QT5: C:\Qt\5.14\msvc2017_64
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
      ARCHITECTURE: x86_64
      WARNINGS_AS_ERRORS: ON

cache:
    - 3rd-party/build/opencv -> 3rd-party/make-opencv.bat       # don't rebuild unless the make script changes
    - 3rd-party/build/expat -> 3rd-party/make-expat.bat         # don't rebuild unless the make script changes
    - 3rd-party/build/exiv2 -> 3rd-party/make-exiv2.bat         # don't rebuild unless the make script changes
    - 3rd-party/build/quazip -> 3rd-party/make-quazip.bat       # don't rebuild unless the make script changes
    - 3rd-party/build/libraw -> 3rd-party/make-libraw.bat       # don't rebuild unless the make script changes
    - 3rd-party/build/imageformats -> 3rd-party/make.bat        # don't rebuild unless the make script changes

install:
    - git submodule update --init --recursive
    - call "%VCVARS%"
    # build dependencies
    - call 3rd-party/make.bat %QT5%
 
build_script:
    - call make-nomacs.bat %QT5%

after_build:
    - cd installer
    - dir
    - call make-installer.bat
    - cd C:/OpenSSL-v111-Win64/bin
    - dir

artifacts:
    - path: 'installer/nomacs.x64'
      name: nomacs-portable
      type: zip

    - path: 'installer/nomacs-setup-x64.msi'
      name: nomacs installer
# - path: 'build\*.exe'
#   name: Basic apps
