image: Visual Studio 2019
configuration: Release
skip_commits:
  files:
    - '.github/*'
    - '.travis.yml'
    - '.gitignore'
    - '*.md'

environment:
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QT5: C:\Qt\5.14\msvc2017_64
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
      ARCHITECTURE: x86_64
      WARNINGS_AS_ERRORS: ON

cache:
    - 3rd-party/build/opencv -> 3rd-party/opencv/CMakeLists.txt # don't rebuild unless the cmake config changes
    - 3rd-party/build/expat -> 3rd-party/expat/CMakeLists.txt # don't rebuild unless the cmake config changes
    - 3rd-party/build/exiv2 -> 3rd-party/exiv2/CMakeLists.txt # don't rebuild unless the cmake config changes
    - 3rd-party/build/quazip -> 3rd-party/quazip/CMakeLists.txt # don't rebuild unless the cmake config changes

install:
    - git submodule update --init --recursive
    - call "%VCVARS%"
    # build dependencies
    - call 3rd-party/make.bat %QT5%
    - call configure-nomacs.bat %QT5%
 
build:
    project: build/nomacs/nomacs.sln
    parallel: true
    verbosity: minimal

after_build:
    - cd installer
    - dir
    # - dir nomacs.x64
    # - make-installer.bat
    # - cd..

# artifacts:
# - path: 'installer\nomacs-setup-x64.msi'
#   name: nomacs installer
# - path: 'build\*.exe'
#   name: Basic apps
