image: Visual Studio 2019
configuration: Release
skip_commits:
  files:
    - '.github/*'
    - '.travis.yml'
    - '.gitignore'
    - '*.md'

environment:
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QT5: C:\Qt\5.14\msvc2017_64
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
      ARCHITECTURE: x86_64
      WARNINGS_AS_ERRORS: ON

    certpwd:
      secure: 931hCkba4VFc/e5FRs3XxQ==
    
    test:
      secure: kTgvDuzEpd3AJzXO0ZXCyulOHH4sJjKIWbhYrhW4Um4=

cache:
    - 3rd-party/build/opencv -> 3rd-party/make-opencv.bat       # don't rebuild unless the make script changes
    - 3rd-party/build/expat -> 3rd-party/make-expat.bat         # don't rebuild unless the make script changes
    - 3rd-party/build/exiv2 -> 3rd-party/make-exiv2.bat         # don't rebuild unless the make script changes
    - 3rd-party/build/quazip -> 3rd-party/make-quazip.bat       # don't rebuild unless the make script changes
    - 3rd-party/build/libraw -> 3rd-party/make-libraw.bat       # don't rebuild unless the make script changes
    - 3rd-party/build/imageformats -> 3rd-party/make.bat        # I had issues with -p

install:
    - call echo %test%%
    - call echo "%test%"
    - call echo %
    - call echo \%
    - git submodule update --init --recursive
    - git lfs pull
    - call "%VCVARS%"
    # build dependencies
    - call 3rd-party/make.bat %QT5%
 
build_script:
    - call make-nomacs.bat %QT5%

after_build:
    - cd installer
    # sign
    - call echo %test%
    # @markus don't question the extra % - it's correct...
    # - call signtool sign /f ./cert-2018.p12 /p %certpwd% /a ./nomacs.x64/nomacs.exe
    - call make-installer.bat
    # - call signtool sign /f ./cert-2018.p12 /p %certpwd% /a ./nomacs-setup-x64.msi

artifacts:
    - path: 'installer/nomacs.x64'
      name: nomacs-portable
      type: zip

    - path: 'installer/nomacs-setup-x64.msi'
      name: nomacs-installer

deploy:
    # Deploy to GitHub
    - provider: GitHub
      artifact: nomacs-installer,nomacs-portable
      auth_token:
        secure: KkKZpdw2KAV3Neyr0jr/7fyq20RiK982n34O+7weSxsDfLB4lZ2IG5UIgVThxEiy
      draft: true
      prerelease: false
      on:
        branch: master
        APPVEYOR_REPO_TAG: true