image: Visual Studio 2019
configuration: Release
skip_commits:
  files:
    - '.github/*'
    - '.travis.yml'
    - '.gitignore'
    - '*.md'

environment:
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      QT5: C:\Qt\5.14.1\msvc2017_64
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
      ARCHITECTURE: x86_64
      WARNINGS_AS_ERRORS: ON

cache:
    - 3rd-party/opencv/build -> 3rd-party/opencv/CMakeLists.txt # don't rebuild unless the cmake config changes
    - 3rd-party/expat/build -> 3rd-party/expat/CMakeLists.txt # don't rebuild unless the cmake config changes
    - 3rd-party/exiv2/build -> 3rd-party/exiv2/CMakeLists.txt # don't rebuild unless the cmake config changes

install:
    - git submodule update --init --recursive
    # my machine:
    #  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"
    - call "%VCVARS%"
    # build dependencies
    - call 3rd-party/make.bat %QT5%
    - cmd: 
        "cmake 
        -DENABLE_TRANSLATIONS=ON 
        -DCMAKE_PREFIX_PATH=
            \"%QT5%;
            ../3rd-party/exiv2/build;
            ../3rd-party/opencv/build;
            ../3rd-party/quazip/build\" 
        -DENABLE_QUAZIP=OFF -DENABLE_RAW=OFF 
        -B build 
        ImageLounge
        "
 
build:
    project: build/nomacs.sln
    parallel: true
    verbosity: minimal

after_build:
    - cd installer
    - dir
    - dir nomacs.x64
    - make-installer.bat
    - cd..

artifacts:
- path: 'installer\nomacs-setup-x64.msi'
  name: nomacs installer
# - path: 'build\*.exe'
#   name: Basic apps
