--- 
name: zlib 1.2.5 Source
platform_id: all
platform_version: all
distribution_file_uuid_string: openlogic-zlib-1.2.5-all-src-1
platform_vendor: all
version_visibility: public
description: zlib 1.2.5 Source
platform_arch: all
distribution_file_uuid: 20be936beb27800032fab193251a383cb8ea8cb3e7f5cfd1110a84dbe4c74358
distribution_version: 1
distribution_flavor: ""
distribution_raw_file: 1.2.5/zlib-1.2.5.tar.gz
notify: "yes"
package_version: 1.2.5
package_id: zlib
release_date: "2010-09-28"
distribution_notes: ""
distribution_type: src
