
  name: nomacs-image-lounge
  version: 3.11
  summary: nomacs is a free, open source image viewer.
  description: |
    You can use it for viewing all common image formats 
    including RAW and psd images. nomacs is licensed 
    under the GNU General Public License v3 and 
    available for Windows, Linux, FreeBSD, Mac, and OS/2.
  icon: ./ImageLounge/nomacs.svg

  # grade: devel # must be 'stable' to release into candidate/stable channels
  # confinement: devmode # use 'strict' once you have the right plugs and slots
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  apps:
    nomacs:
      command: desktop-launch nomacs

  parts:
    nomacs:
      stage-packages:
        - libc6
        - libraw-dev
        - libtbb-dev
        - libjasper-dev
        - libexiv2-dev
        - libqt5printsupport5
        - libqt5concurrent5
      build-packages:
        - debhelper
        - cdbs
        - qt5-qmake
        - qttools5-dev-tools
        - qt5-default
        - qttools5-dev
        - libqt5svg5-dev
        - qt5-image-formats-plugins
        - libexiv2-dev
        - libraw-dev
        - libopencv-dev
        - cmake
        - libtiff-dev
        - libquazip-dev
        - libwebp-dev
        - git
        - g++
        - libzip-dev
      plugin: cmake
      source: ./ImageLounge
      configflags: 
        - -DCMAKE_BUILD_TYPE=Release
        - -DENABLE_QUAZIP=OFF # fixme  
      after: [desktop-qt5]      
